---
plugins:
  - rubocop-boochtek

# Ignore some files. NOTE: Exclude does not add to any existing Exclude directives.
AllCops:
  Exclude:
    - "church*.rb"
    - "vendor/**/*"
  NewCops: disable

# Allow longer lines.
Layout/LineLength:
  Max: 160

# Use `{}` for blocks that return a value; otherwise use `do` and `end`.
# We make a few exceptions, mostly for RSpec. And for grammar and transform rules.
Style/BlockDelimiters:
  EnforcedStyle: semantic
  FunctionalMethods:
    - expect
  AllowedMethods:
    - let
    - let!
    - subject
    - rule
    - rule!
    - terminal
    - terminal!

# Allow non-ASCII identifiers, and in comments.
Naming/AsciiIdentifiers:
  Enabled: false

# Some of our classes are going to be long.
Metrics/ClassLength:
  Max: 250

# Sometimes we need to pass a block down recursively, so allow expressing that.
Performance/RedundantBlockCall:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/stone/type/*

# Not sure why `∧` and `∨` are problematic, even after allowing non-ASCII identifiers.
# Also allow `builtin_ClassName` methods.
Naming/MethodName:
  Exclude:
    - lib/extensions/boolean.rb
    - lib/stone/top.rb

# Allow numbered variables in record field comparisons (field1_0, field2_0).
Naming/VariableNumber:
  Exclude:
    - lib/stone/ast/function_call.rb

# I don't believe `module_function` should be outdented like `private`, but there's no way to turn it off for just `module_function`.
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent
  Exclude:
    - lib/stone/top.rb

# Allow `expr = expr + x` in this particular file, to parallel `expr = x + expr` that's right next to it.
Style/SelfAssignment:
  Exclude:
    - lib/stone/ast/binary_operation.rb

# The `grammar` and `transforms` methods are DSLs; don't worry about their size/complexity.
Metrics/AbcSize:
  AllowedMethods:
    - grammar
    - transforms
Metrics/MethodLength:
  AllowedMethods:
    - grammar
    - transforms
Metrics/PerceivedComplexity:
  AllowedMethods:
    - grammar
    - transforms
Metrics/CyclomaticComplexity:
  AllowedMethods:
    - grammar
    - transforms

Style/PercentLiteralDelimiters:
  Exclude:
    - "lib/stone/ast/binary_operation.rb"

# Be a bit more lenient with RSpec: don't require filename to match class; allow more than 1 expectation per example.
RSpec/SpecFilePathFormat:
  Enabled: false
RSpec/DescribedClass:
  Enabled: false
RSpec/DescribeClass:
  Enabled: false

# RuboCop doesn't like the way we use the `parse_as` custom matcher.
RSpec/ExpectActual:
  Exclude:
    - "spec/unit/parser/**/**.rb"

# I like to put 2 spaces before inline comments.
Layout/ExtraSpacing:
  Enabled: false

# Allow use of a single `module_function` instead of prepending it to every method.
# Unfortunately, we can't turn this off only for `module_function`.
Style/AccessModifierDeclarations:
  Enabled: false
